version: "3"

services:
    api:
        build: ./api
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./api:/usr/src/api
        environment:
            - FLASK_ENV=development
            - FLASK_APP=/usr/src/api
            - FLASK_DEBUG=1
            - DB_CONNECT_STR=postgresql+psycopg2://medieteknik:rgb@db/medieteknikdev
    app:
        build: ./app
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./app/src:/usr/src/app/src
            - ./app/public:/usr/src/app/public
        environment:
          - CHOKIDAR_USEPOLLING=true
        links:
            - "api:api"

    db:
        image: postgres:10.5
        container_name: postgres
        ports:
            - 5432:5432
        expose:
            - 5432
        environment:
            - POSTGRES_DB=medieteknikdev
            - POSTGRES_USER=medieteknik
            - POSTGRES_PASSWORD=rgb
        volumes:
            - './db:/docker-entrypoint-initdb.d/'
