version: "3"

services:
    api:
        build: ./api
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./api:/usr/src/api
        environment:
            - DB_CONNECT_STR=postgresql+psycopg2://medieteknik:rgb@db/medieteknikdev
            - GUNICORN_CMD_ARGS="--reload"
    app:
        build: ./app
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./app/src:/usr/src/app/src
            - ./app/public:/usr/src/app/public
        links:
            - "api:api"

    db:
        image: postgres:10.5
        container_name: postgres
        ports:
            - 5432:5432
        expose:
            - 5432
        environment:
            - POSTGRES_DB=medieteknikdev
            - POSTGRES_USER=medieteknik
            - POSTGRES_PASSWORD=rgb
        volumes:
            - './db:/docker-entrypoint-initdb.d/'

    web:
        image: nginx:1.17.4
        container_name: web
        restart: unless-stopped
        tty: true
        ports:
            - 8080:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
            - api
