import { fontFigtree } from '@/app/fonts'
import '@shared/styles/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={`${fontFigtree.className}`}
      style={{
        WebkitFontSmoothing: 'antialiased',
      }}
    >
      <body>{children}</body>
    </html>
  )
}
