import { fontFigtree } from '@/app/fonts'
import '@medieteknik/tailwindcss-config/globals.css'
import type { Metadata } from 'next'
import { ViewTransitions } from 'next-view-transitions'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html
        lang='en'
        suppressHydrationWarning
        className={`${fontFigtree.className}`}
        style={{
          WebkitFontSmoothing: 'antialiased',
        }}
      >
        <body>{children}</body>
      </html>
    </ViewTransitions>
  )
}
