name: Deploy frontend

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.4
    - run: npm install
      working-directory: app
    - run: npm run build
      working-directory: app
      env:
        CI: false
        NODE_OPTIONS: --max_old_space_size=4096
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: app/build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build
          path: app/build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./app 
